# Generated by Django 3.0.6 on 2020-05-18 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergene', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'allergies',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_Kor', models.CharField(max_length=50)),
                ('name_Eng', models.CharField(max_length=50)),
                ('description_main', models.CharField(max_length=300)),
                ('description_sub', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'drinks',
            },
        ),
        migrations.CreateModel(
            name='Nutrients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kcal', models.DecimalField(decimal_places=1, max_digits=5)),
                ('sat_FAT', models.DecimalField(decimal_places=1, max_digits=5)),
                ('protein', models.DecimalField(decimal_places=1, max_digits=5)),
                ('sodium', models.DecimalField(decimal_places=1, max_digits=5)),
                ('sugar', models.DecimalField(decimal_places=1, max_digits=5)),
                ('caffeine', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
            options={
                'db_table': 'nutrients',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_name', models.CharField(max_length=50)),
                ('size_ml', models.DecimalField(decimal_places=1, max_digits=5)),
                ('size_fluid_ounce', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
            options={
                'db_table': 'sizes',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=2000)),
                ('drink', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Drink')),
            ],
            options={
                'db_table': 'images',
            },
        ),
        migrations.CreateModel(
            name='DrinkAllergen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Allergy')),
                ('drink', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Drink')),
            ],
            options={
                'db_table': 'drinks_allergies',
            },
        ),
        migrations.AddField(
            model_name='drink',
            name='allergenes',
            field=models.ManyToManyField(related_name='containing_drinks', through='products.DrinkAllergen', to='products.Allergy'),
        ),
        migrations.AddField(
            model_name='drink',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Category'),
        ),
        migrations.AddField(
            model_name='drink',
            name='nutrients',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Nutrients'),
        ),
        migrations.AddField(
            model_name='drink',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Size'),
        ),
    ]
